sudo apt install wget 
sudo apt install gcc 
sudo apt install g++ 
sudo apt install make 
sudo apt install flex 
sudo apt install bison 
sudo apt install openssl 
sudo apt install libssl–dev 
sudo apt install perl
sudo apt install perl–base 
sudo apt install perl–modules 
sudo apt install libperl–dev 
sudo apt install libperl4–corelibs–perl  
sudo apt install libwww–perl
sudo apt install libaio1 
sudo apt install libaio–dev 
sudo apt install zlib1g 
sudo apt install zlib1g–dev 
sudo apt install libcap–dev 
sudo apt install cron 
sudo apt install bzip2 
sudo apt install zip 
sudo apt install automake 
sudo apt install autoconf 
sudo apt install libtool 
sudo apt install cmake 
sudo apt install pkg–config 
sudo apt install python
sudo apt install libdb–dev 
sudo apt install libsasl2–dev 
sudo apt install libncurses5 
sudo apt install libncurses5–dev 
sudo apt install libsystemd–dev 
sudo apt install bind9 
sudo apt install dnsutils 
sudo apt install quota 
sudo apt install patch 
sudo apt install logrotate 
sudo apt install rsyslog 
sudo apt install libc6–dev 
sudo apt install libexpat1–dev 
sudo apt install libcrypt–openssl–rsa–perl 
sudo apt install curl 
sudo apt install libnuma–dev 
sudo apt install libnuma1
